# Generated by Django 5.2.6 on 2025-10-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poma',
            name='amount',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
