# Generated by Django 5.2.6 on 2025-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_poma_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poma',
            name='amount',
            field=models.IntegerField(max_length=99),
        ),
    ]
