# Generated by Django 5.2.6 on 2025-10-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_poma_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poma',
            name='amount',
        ),
    ]
