# Generated by Django 5.2.6 on 2025-10-17 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_poma_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='poma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
