# Generated by Django 6.0.7 on 2026-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
