# Generated by Django 6.0.7 on 2026-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_telegramprofile_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
