# Generated by Django 6.0.7 on 2026-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='prize',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
