# Generated by Django 6.0.7 on 2026-09-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_alter_goal_description_alter_goal_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='goal_type',
            field=models.CharField(choices=[('steps', 'Конкретные шаги'), ('numeric', 'Числовой счетчик')], default='steps', max_length=10),
        ),
        migrations.AddField(
            model_name='step',
            name='target_value',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='card_color',
            field=models.CharField(default='pink', max_length=20),
        ),
    ]
