# Generated by Django 6.0.7 on 2026-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_step_current_value_step_goal_type_step_target_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='step',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='step',
            name='target_value',
        ),
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('steps', 'Конкретные шаги'), ('numeric', 'Числовой счетчик')], default='steps', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.IntegerField(default=100),
        ),
    ]
