# Generated by Django 6.0.7 on 2026-09-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_remove_step_current_value_remove_step_goal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_value',
        ),
    ]
