# Generated by Django 6.0.7 on 2026-09-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_remove_goal_current_value_remove_goal_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('steps', 'Конкретные шаги'), ('numeric', 'Числовой счетчик')], default='steps', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.IntegerField(default=100),
        ),
    ]
